//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmissionGrade
    {
        public int SubmissionId { get; set; }
        public Nullable<decimal> Grade { get; set; }
        public string TeacherId { get; set; }
        public string Feedback { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Submission Submission { get; set; }
    }
}
